baseURL = "https://myblog-virid-chi.vercel.app/"
languageCode = "zh-cn"
title = "林理洵的blog"
theme = "PaperMod"

[params]
    description = "这是我记录生活和技术的地方"
    
    # --- 个人主页模式设置 ---
    [params.profileMode]
        enabled = true  # 如果想直接看文章，把这里改成 false
        title = "你好，我是林理洵"
        subtitle = "梦里不觉秋已深，余情岂是为他人"
        imageUrl = "1691750620739.png" # 确保图片在 static 文件夹里
        imageWidth = 120
        imageHeight = 120

        # 添加一个按钮，让人能点进去看文章
        [[params.profileMode.buttons]]
            name = "开始阅读"
            url = "/posts"

    # --- 社交图标 ---
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/linlixun-lin"
    [[params.socialIcons]]
        name = "bilibili"
        url = "https://space.bilibili.com/471403876?spm_id_from=333.1007.0.0"

    # --- 网站图标 ---
    [params.assets]
        favicon = "favicon.ico"
        ShowReadingTime = true    # 显示阅读时长
        ShowWordCount = true      # 显示字数
        ShowBreadCrumbs = true    # 显示面包屑导航
        ShowPostNavLinks = true   # 显示“上一篇/下一篇”按钮

# --- 菜单栏 (注意：这部分要放在最外层，不要缩进到 params 里) ---
[menu]
    [[menu.main]]
        identifier = "archives"
        name = "归档"
        url = "/archives/"
        weight = 10
    [[menu.main]]
        identifier = "search"
        name = "搜索"
        url = "/search/"
        weight = 20
    [[menu.main]]
        identifier = "about"
        name = "关于"
        url = "/about/"
        weight = 30
[params.comments]
    enabled = true
 [outputs]
    home = ["HTML", "RSS", "JSON"]
